---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml

build_dockers:
  stage: build
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  hooks:
    pre_get_sources_script:
      - apk add --no-cache openssh
  before_script:
    - docker info
    - apk add --no-cache bash moreutils git go curl just
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    BASE_CONTAINER_REGISTRY: "docker.osdc.io"
  script:
    - /bin/bash build.sh -b "$CI_COMMIT_BRANCH" -n "$CI_COMMIT_SHORT_SHA"
